# Generated by Django 4.2 on 2026-01-06 12:51

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('symbol', models.CharField(max_length=20, unique=True)),
                ('description', models.TextField(blank=True)),
                ('category', models.CharField(choices=[('crypto', 'Cryptocurrency'), ('forex', 'Forex'), ('futures', 'Futures'), ('stock', 'Stock')], max_length=20)),
                ('current_price', models.DecimalField(decimal_places=6, default=0, max_digits=20)),
                ('previous_price', models.DecimalField(decimal_places=6, default=0, max_digits=20)),
                ('change_percentage', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('min_investment', models.DecimalField(decimal_places=2, default=10, max_digits=20)),
                ('max_investment', models.DecimalField(decimal_places=2, default=100000, max_digits=20)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('icon', models.ImageField(blank=True, null=True, upload_to='assets/icons/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['display_order', 'name'],
            },
        ),
    ]
