# Generated by Django 4.2 on 2026-01-06 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='allowed_durations',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='asset',
            name='return_rate_12h',
            field=models.DecimalField(decimal_places=2, default=6.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='asset',
            name='return_rate_1h',
            field=models.DecimalField(decimal_places=2, default=0.5, max_digits=5),
        ),
        migrations.AddField(
            model_name='asset',
            name='return_rate_24h',
            field=models.DecimalField(decimal_places=2, default=12.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='asset',
            name='return_rate_3h',
            field=models.DecimalField(decimal_places=2, default=1.5, max_digits=5),
        ),
        migrations.AddField(
            model_name='asset',
            name='return_rate_6h',
            field=models.DecimalField(decimal_places=2, default=3.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='asset',
            name='risk_level',
            field=models.CharField(choices=[('low', 'Low Risk'), ('medium', 'Medium Risk'), ('high', 'High Risk'), ('very_high', 'Very High Risk')], default='medium', max_length=20),
        ),
    ]
